package com.example.appcappappdemo.aca.entity.response

import com.example.appcappappdemo.aca.entity.BaseEntity

class QueryResponseEntity(
    var charset: String = "",
    var device_info: String = "",
    var mch_id: String = "",
    var nonce_str: String = "",
    var result_code: String = "",
    var sign: String = "",
    var sign_type: String = "",
    var status: String = "",
    var trade_state: String = "",
    var version: String = "",
    var message: String = "",
    var err_code: String = "",
    var err_msg: String = "",
    var trade_type: String = "",
    var trade_state_desc: String = "",
    var pay_result: String = "",
    var appid: String = "",
    var sub_appid: String = "",
    var openid: String = "",
    var sub_openid: String = "",
    var is_subscrib: String = "",
    var sub_is_subscribe: String = "",
    var payment_inst: String = "",
    var transaction_id: String = "",
    var out_trade_no: String = "",
    var total_fee: String = "",
    var coupon_fee: String = "",
    var fee_type: String = "",
    var attach: String = "",
    var bank_type: String = "",
    var bank_billno: String = "",
    var time_end: String = "",
    var cash_fee: String = "",
    var cash_fee_type: String = "",
    var rate: String = "",
    var local_fee_type: String = "",
    var local_total_fee: String = "",
    var order_fee: String = ""
) : BaseEntity()